version: "3.8"
services:
  main:
    build:
      context: ./main
    command: /app/entrypoint.sh
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/i2c-1:/dev/i2c-1"

  redis_proxy:
    build:
      context: ./redis_proxy
      dockerfile: ../main/Dockerfile
    command: /app/entrypoint.sh
  
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
      